### ISSUE TITLE
Question: Does it support playing YouTube videos?

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [12207480/TYVideoPlayer#1]
Nice work on the library! Can you please let me know whether you support YouTube videos as well?

**Comment by 12207480** [comment]
Do you have YouTube video url ? I can test it

**Comment by AnnieNinaJoyceV** [comment]
Thanks :), here is a sample Youtube url - https://www.youtube.com/watch?v=PCwL3-hkKrg
